version: 2

project_name: gkn

builds:
  - id: gkn
    main: ./cmd/gkn
    binary: gkn
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.Version={{ .Version }}

archives:
  - id: gkn
    ids:
      - gkn
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"

sboms:
  - id: default
    artifacts: archive
    disable: false

signs:
  - id: cosign
    cmd: cosign
    signature: "${artifact}.sigstore.json"
    artifacts: checksum
    args:
      - sign-blob
      - --bundle=${signature}
      - ${artifact}
      - --yes

release:
  prerelease: auto

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

brews:
  - name: gkn
    ids:
      - gkn
    homepage: "https://github.com/TT-AIXion/github-kanri"
    description: "GitHub リポジトリ管理 CLI"
    license: "MIT"
    url_template: "https://github.com/TT-AIXion/github-kanri/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    directory: Formula
    install: |
      bin.install "gkn"
    test: |
      system "#{bin}/gkn", "version"
    repository:
      owner: "{{ .Env.HOMEBREW_TAP_OWNER }}"
      name: "{{ .Env.HOMEBREW_TAP_NAME }}"
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    skip_upload: "{{ if or (eq .Env.HOMEBREW_TAP_OWNER \"\") (eq .Env.HOMEBREW_TAP_NAME \"\") (eq .Env.HOMEBREW_TAP_TOKEN \"\") }}true{{ else }}auto{{ end }}"

homebrew_casks:
  - name: gkn
    ids:
      - gkn
    binaries:
      - gkn
    homepage: "https://github.com/TT-AIXion/github-kanri"
    description: "GitHub リポジトリ管理 CLI"
    license: "MIT"
    url:
      template: "https://github.com/TT-AIXion/github-kanri/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
      verified: "github.com/TT-AIXion/github-kanri"
    repository:
      owner: "{{ .Env.HOMEBREW_TAP_OWNER }}"
      name: "{{ .Env.HOMEBREW_TAP_NAME }}"
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    skip_upload: "{{ if or (eq .Env.HOMEBREW_TAP_OWNER \"\") (eq .Env.HOMEBREW_TAP_NAME \"\") (eq .Env.HOMEBREW_TAP_TOKEN \"\") }}true{{ else }}auto{{ end }}"
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gkn"]
          end
