name: Bug report
description: Report a reproducible problem
title: "bug: "
labels: ["bug"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened?
      placeholder: Clear, short description
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Include commands and inputs
      placeholder: |
        1. ...
        2. ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: OS, Git, gkn version
      placeholder: |
        macOS 14.x
        git --version
        gkn version
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs or output
      description: Paste relevant output. If possible include `--json` output.
      render: shell
